// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSlCkuluNlDXdw04ODLC-q6OFyBKecvaY',
    appId: '1:872525258393:web:bd72e8ccffa9be1766a208',
    messagingSenderId: '872525258393',
    projectId: 'cuaca-app-4ec04',
    authDomain: 'cuaca-app-4ec04.firebaseapp.com',
    storageBucket: 'cuaca-app-4ec04.firebasestorage.app',
    measurementId: 'G-65B1L77DEC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1RPnNMblD6uO2YT_QPmz0mcWZUlCW3g0',
    appId: '1:872525258393:android:8bdb7c7ea56411bb66a208',
    messagingSenderId: '872525258393',
    projectId: 'cuaca-app-4ec04',
    storageBucket: 'cuaca-app-4ec04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQD5W_FBBfMFAsSTGlPOCcANGJrO7BMqg',
    appId: '1:872525258393:ios:24a026ee92c72a9166a208',
    messagingSenderId: '872525258393',
    projectId: 'cuaca-app-4ec04',
    storageBucket: 'cuaca-app-4ec04.firebasestorage.app',
    iosBundleId: 'com.example.flutterAplikasiCuaca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQD5W_FBBfMFAsSTGlPOCcANGJrO7BMqg',
    appId: '1:872525258393:ios:24a026ee92c72a9166a208',
    messagingSenderId: '872525258393',
    projectId: 'cuaca-app-4ec04',
    storageBucket: 'cuaca-app-4ec04.firebasestorage.app',
    iosBundleId: 'com.example.flutterAplikasiCuaca',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSlCkuluNlDXdw04ODLC-q6OFyBKecvaY',
    appId: '1:872525258393:web:8591ca220d90a44666a208',
    messagingSenderId: '872525258393',
    projectId: 'cuaca-app-4ec04',
    authDomain: 'cuaca-app-4ec04.firebaseapp.com',
    storageBucket: 'cuaca-app-4ec04.firebasestorage.app',
    measurementId: 'G-FGQ8PSD2CJ',
  );
}
